#!/usr/bin/env python3

import argparse
from pathlib import Path


def escape_byte(byte: int) -> str:
    if byte == 0x0A:
        return r"\n"
    if byte == 0x09:
        return r"\t"
    if byte == 0x0D:
        return r"\r"
    if byte == 0x22:
        return r"\""
    if byte == 0x5C:
        return r"\\"
    if 0x20 <= byte <= 0x7E:
        return chr(byte)
    return f"\\x{byte:02x}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--variable", required=True)
    args = parser.parse_args()

    data = Path(args.input).read_bytes()
    lines = [
        "/* Generated by tools/text_to_c_header.py. */",
        f"static const char {args.variable}[] =",
    ]

    for raw_line in data.splitlines(keepends=True):
        chunk = "".join(escape_byte(byte) for byte in raw_line)
        lines.append(f'    "{chunk}"')
    lines.append("    ;")
    lines.append("")

    Path(args.output).write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
